0:
  nbits_key: 2
  nbits_value: 2
1:
  nbits_key: 4
  nbits_value: 4
2:
  nbits_key: 4
  nbits_value: 4
3:
  nbits_key: 4
  nbits_value: 4
4:
  nbits_key: 2
  nbits_value: 2
5:
  nbits_key: 4
  nbits_value: 2
6:
  nbits_key: 4
  nbits_value: 2
7:
  nbits_key: 4
  nbits_value: 4
8:
  nbits_key: 4
  nbits_value: 2
9:
  nbits_key: 4
  nbits_value: 2
10:
  nbits_key: 4
  nbits_value: 2
11:
  nbits_key: 4
  nbits_value: 2
12:
  nbits_key: 4
  nbits_value: 2
13:
  nbits_key: 8
  nbits_value: 4
14:
  nbits_key: 4
  nbits_value: 2
15:
  nbits_key: 4
  nbits_value: 2
16:
  nbits_key: 4
  nbits_value: 2
17:
  nbits_key: 8
  nbits_value: 4
18:
  nbits_key: 4
  nbits_value: 2
19:
  nbits_key: 4
  nbits_value: 2
20:
  nbits_key: 4
  nbits_value: 2
21:
  nbits_key: 4
  nbits_value: 2
22:
  nbits_key: 4
  nbits_value: 2
23:
  nbits_key: 4
  nbits_value: 2
24:
  nbits_key: 4
  nbits_value: 2
25:
  nbits_key: 2
  nbits_value: 2
26:
  nbits_key: 4
  nbits_value: 2
27:
  nbits_key: 2
  nbits_value: 2
28:
  nbits_key: 4
  nbits_value: 2
29:
  nbits_key: 4
  nbits_value: 4
30:
  nbits_key: 4
  nbits_value: 2
31:
  nbits_key: 4
  nbits_value: 4